################################################################################
# Automatically-generated file. Do not edit!
################################################################################

ASM_UPPER_SRCS := 
O_SRCS := 
ELF_SRCS := 
SX_SRCS := 
LINKER_SCRIPT := 
JMP_UPPER_SRCS := 
P_UPPER_SRCS := 
SRC_SRCS := 
JMP_SRCS := 
FSY_UPPER_SRCS := 
PP_UPPER_SRCS := 
OBJ_UPPER_SRCS := 
ASM_SRCS := 
SX_UPPER_SRCS := 
O_UPPER_SRCS := 
S_UPPER_SRCS := 
ELF_UPPER_SRCS := 
C_UPPER_SRCS := 
OBJ_SRCS := 
S_SRCS := 
PP_SRCS := 
SRC_UPPER_SRCS := 
FSY_SRCS := 
P_SRCS := 
C_SRCS := 
JMP_DEPS := 
FSY_DEPS := 
C_UPPER_DEPS := 
SECONDARY_SIZE := 
SRC_UPPER_DEPS := 
P_UPPER_DEPS := 
S_DEPS := 
PP_UPPER_DEPS := 
P_DEPS := 
FSY_UPPER_DEPS := 
C_DEPS := 
SRC_DEPS := 
JMP_UPPER_DEPS := 
PP_DEPS := 
SX_DEPS := 
ASM_UPPER_DEPS := 
SX_UPPER_DEPS := 
OBJS := 
SECONDARY_FLASH := 
ASM_DEPS := 
SREC := 
S_UPPER_DEPS := 
MAP := 

# Every subdirectory with source files must be described here
SUBDIRS := \
src/gui \
src \
src/hardware \
src/led_control \
src/synergy_gen \
synergy/board/s7g2_sk \
synergy/ssp/src/bsp/cmsis/Device/RENESAS/S7G2/Source \
synergy/ssp/src/bsp/mcu/all \
synergy/ssp/src/bsp/mcu/s7g2 \
synergy/ssp/src/driver/r_cgc \
synergy/ssp/src/driver/r_dmac \
synergy/ssp/src/driver/r_dtc \
synergy/ssp/src/driver/r_elc \
synergy/ssp/src/driver/r_glcd \
synergy/ssp/src/driver/r_icu \
synergy/ssp/src/driver/r_ioport \
synergy/ssp/src/driver/r_jpeg_common \
synergy/ssp/src/driver/r_jpeg_decode \
synergy/ssp/src/driver/r_qspi \
synergy/ssp/src/driver/r_riic \
synergy/ssp/src/driver/r_sci_spi \
synergy/ssp/src/framework/el/nx_md5 \
synergy/ssp/src/framework/el/nxd_application_layer/nxd_dhcp \
synergy/ssp/src/framework/el/nxd_application_layer/nxd_http_server \
synergy/ssp/src/framework/sf_el_gx \
synergy/ssp/src/framework/sf_el_nx \
synergy/ssp/src/framework/sf_el_nx/phy \
synergy/ssp/src/framework/sf_el_ux \
synergy/ssp/src/framework/sf_external_irq \
synergy/ssp/src/framework/sf_i2c \
synergy/ssp/src/framework/sf_jpeg_decode \
synergy/ssp/src/framework/sf_tes_2d_drw \
synergy/ssp/src/framework/sf_touch_panel_v2 \
synergy/ssp/src/framework/tes/dave2d \
synergy/ssp_supplemental/touch_drivers/touch_panel_chip_sx8654 \

