/*******************************************************************************/
/*  This file is auto-generated by Azure RTOS GUIX Studio. Do not edit this    */
/*  file by hand. Modifications to this file should only be made by running    */
/*  the Azure RTOS GUIX Studio application and re-generating the application   */
/*  resource file(s). For more information please refer to the Azure RTOS GUIX */
/*  Studio User Guide, or visit our web site at azure.com/rtos                 */
/*                                                                             */
/*  GUIX Studio Revision 6.4.0.0                                               */
/*  Date (dd.mm.yyyy): 16.12.2025   Time (hh:mm): 00:49                        */
/*******************************************************************************/


#ifndef _GUIAPP_DISPLAY_1_RESOURCES_H_
#define _GUIAPP_DISPLAY_1_RESOURCES_H_

#include "gx_api.h"

/* Display and theme definitions                                               */

#define DISPLAY_1 0
#define DISPLAY_1_COLOR_FORMAT GX_COLOR_FORMAT_565RGB
#define DISPLAY_1_X_RESOLUTION 256
#define DISPLAY_1_Y_RESOLUTION 320
#define DISPLAY_1_THEME_1 0
#define DISPLAY_1_THEME_TABLE_SIZE 1

/* Language definitions                                                        */

#define LANGUAGE_ENGLISH 0
#define DISPLAY_1_LANGUAGE_TABLE_SIZE 1

/* Color ID definitions                                                        */

#define GX_COLOR_ID_WHITE 29
#define GX_COLOR_ID_BLACK 30
#define GX_COLOR_ID_PBAR 31
#define DISPLAY_1_COLOR_TABLE_SIZE 32

/* Font ID definitions                                                         */

#define DISPLAY_1_FONT_TABLE_SIZE 4

/* Pixelmap ID definitions                                                     */

#define DISPLAY_1_PIXELMAP_TABLE_SIZE 5

/* String Ids                                                                  */

#define GX_STRING_ID_HELLO_WORLD 1
#define GX_STRING_ID_CHECKBOX_TEXT 2
#define GX_STRING_ID_BUTTON_DISABLED 3
#define GX_STRING_ID_BUTTON_ENABLED 4
#define GX_STRING_ID_INSTRUCT_CHECKBOX 5
#define GX_STRING_ID_WINDOW1 6
#define GX_STRING_ID_WINDOW2 7
#define GX_STRING_ID_INSTRUCT_BUTTON 8
#define GX_STRING_ID_STRING_1 9
#define GX_STRING_ID_STRING_2 10
#define GX_STRING_ID_STRING_3 11
#define GX_STRING_ID_STRING_4 12
#define GX_STRING_ID_STRING_5 13
#define DISPLAY_1_STRING_TABLE_SIZE 14

#endif                                       /* sentry                         */
