#pragma once
/* Auto-generated by gen_web_assets.py. */

#ifdef __cplusplus
extern "C" {
#endif
#include "stdio.h"
#include "fx_api.h"

extern const unsigned char WEB_INDEX_HTML[];
extern const unsigned int  WEB_INDEX_HTML_LEN;
extern const unsigned char WEB_APP_HTML[];
extern const unsigned int  WEB_APP_HTML_LEN;
extern const unsigned char WEB_FILE_MANAGER_JS[];
extern const unsigned int  WEB_FILE_MANAGER_JS_LEN;

UINT webui_provision_to_usb(FX_MEDIA * media);

#ifdef __cplusplus
}
#endif
